spring:
  application:
    name: webdav
  datasource:
    url: jdbc:h2:file:./data/webdav;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  templates:
    storage-path: ./data/templates
